# Generated by Django 3.0.4 on 2020-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200407_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'To Do'), (2, 'In progress'), (3, 'Done')], default=1),
        ),
    ]
