# Generated by Django 3.0.4 on 2020-04-26 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200420_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='planned_story_points',
        ),
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
