# Generated by Django 3.0.4 on 2020-05-03 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200420_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sprint',
        ),
        migrations.AddField(
            model_name='sprint',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='sprints', to='projects.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'To Do'), (1, 'In progress'), (2, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
