# Generated by Django 3.0.4 on 2020-05-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='sprints',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.Sprint'),
        ),
    ]
