# Generated by Django 3.0.4 on 2020-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200504_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sprints',
        ),
        migrations.AddField(
            model_name='sprint',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='sprints', to='projects.Task'),
        ),
    ]
