# Generated by Django 3.0.4 on 2020-05-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200504_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='planned_story_points',
        ),
    ]
